name: Pull Request

# "This run was triggered by the "push" event, which is unsupported.
#  Please ensure you are using the "pull_request" event for this workflow."
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    uses: percebus/github-actions-common/.github/workflows/dependency-review.yml@main

  # FIXME:
  # "ERROR:pip_audit._virtual_env:internal pip failure:   error: subprocess-exited-with-error
  #   raise NotImplementedError, 'emit must be implemented '\
  #   SyntaxError: invalid syntax"
  #
  # pip-audit:
  #   # uses: percebus/github-actions-pipx/.github/workflows/run_pip-audit_detect.yml@main  # TODO
  #
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: percebus/github-actions-common/.github/actions/checkout@main
  #     - uses: percebus/github-actions-python/.github/actions/setup@main
  #     - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main
  #
  #     - name: pip-audit
  #       # run: pipx run -- pip-audit . --locked  # FIXME "ERROR:pip_audit._cli:no lockfiles found in ."
  #       run: |
  #         pip install pip-audit
  #         pip-audit .

  #
  # package.json dependencies
  npm_audit:
    uses: percebus/github-actions-npm/.github/workflows/audit.yml@main
